[general]
bars = 64
bar_width = 2
bar_spacing = 1
framerate = 144
sensitivity = 100
autosens = 1

[input]
method = pulse
source = auto

[output]
method = ncurses
channels = mono
mono_option = average

[smoothing]
integral = 95
monstercat = 1
noise_reduction = 0.88
waves = 0
gravity = 140

[color]
gradient = 1
gradient_count = 8
gradient_color_1 = '#440000'
gradient_color_2 = '#990000'
gradient_color_3 = '#FF0000'
gradient_color_4 = '#FF4400'
gradient_color_5 = '#FF8800'
gradient_color_6 = '#FFAA00'
gradient_color_7 = '#FFCC00'
gradient_color_8 = '#FFEE00'
background = '#0a0a0a'
foreground = '#FFCC00'

