[general]
bars = 64
bar_width = 2
bar_spacing = 1
framerate = 144
sensitivity = 100
autosens = 1

[input]
method = pulse
source = auto

[output]
method = ncurses
channels = mono
mono_option = average

[smoothing]
integral = 95
monstercat = 1
noise_reduction = 0.88
waves = 0
gravity = 140

[color]
gradient = 1
gradient_count = 8
gradient_color_1 = '#1F0606'
gradient_color_2 = '#5E0D0B'
gradient_color_3 = '#9D1911'
gradient_color_4 = '#74463A'
gradient_color_5 = '#E14D29'
gradient_color_6 = '#F96A8C'
gradient_color_7 = '#F8A551'
gradient_color_8 = '#FBDEAF'
background = '#0a0a0a'
foreground = '#F8A551'

