-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local bg = "rgb(150608)"
local primary = "rgb(ff2d55)"
local secondary = "rgb(2c0d0f)"
local accent = "rgb(ffd166)"
local text = "rgb(fff1dd)"
