-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    general = {
        border_size = 4,
        col = {
            active_border = accent .. " " .. primary .. " 45deg",
            inactive_border = secondary,
        },
    },
    decoration = {
        rounding = 8,
        active_opacity = 0.97,
        inactive_opacity = 0.93,
        shadow = {
            enabled = true,
            range = 22,
            render_power = 3,
            color = bg,
        },
    },
    group = {
        col = {
            border_active = accent,
            border_inactive = secondary,
        },
    },
})

