foreground #fff1dd
background #150608
selection_foreground #150608
selection_background #ffd166
cursor #ffd166
cursor_text_color #150608
url_color #e8450c
active_border_color #ffd166
inactive_border_color #7b120f
active_tab_background #e8450c
active_tab_foreground #150608
inactive_tab_background #2c0d0f
inactive_tab_foreground #fff1dd
color0 #150608
color1 #e8450c
color2 #b62614
color3 #ffd166
color4 #ff7f32
color5 #d1303f
color6 #ffc27a
color7 #fff1dd
color8 #4e1715
color9 #ff6530
color10 #cf3a23
color11 #ffe08f
color12 #ff9950
color13 #f05863
color14 #ffd7a8
color15 #fff7eb
