# Kanagawa
foreground              #dcd7ba
background              #1f1f28
selection_foreground    #dcd7ba
selection_background    #2d4f67
cursor                  #c8c093
cursor_text_color       #1f1f28
url_color               #7fb4ca

active_border_color     #ffa066
inactive_border_color   #16161d
active_tab_background   #ffa066
active_tab_foreground   #1f1f28
inactive_tab_background #16161d
inactive_tab_foreground #727169

color0  #090618
color8  #727169

color1  #c34043
color9  #e82424

color2  #76946a
color10 #98bb6c

color3  #c0a36e
color11 #ffa066

color4  #7e9cd8
color12 #7fb4ca

color5  #957fb8
color13 #938aa9

color6  #6a9589
color14 #7aa89f

color7  #c8c093
color15 #dcd7ba
