# Synthwave — retro-future neon grid
foreground              #fefdfe
background              #241b2f
selection_foreground    #fefdfe
selection_background    #45375c
cursor                  #03edf9
cursor_text_color       #241b2f
url_color               #f075b5

active_border_color     #ff7edb
inactive_border_color   #34294f
active_tab_background   #ff7edb
active_tab_foreground   #241b2f
inactive_tab_background #34294f
inactive_tab_foreground #848bbd

color0  #2a2140
color8  #495495

color1  #fe4450
color9  #ff6e67

color2  #72f1b8
color10 #72f1b8

color3  #fede5d
color11 #fede5d

color4  #03edf9
color12 #03edf9

color5  #f075b5
color13 #ff7edb

color6  #7c6ff0
color14 #9a8fff

color7  #fefdfe
color15 #ffffff
