-- TODO: manual review — unexpected token after 'include ./bitbeast.conf'

-- TODO: manual review — unexpected token after 'font_family JetBrainsMono Nerd Font'
-- TODO: manual review — unexpected token after 'font_size 11.5'
-- TODO: manual review — unexpected token after 'bold_font auto'
-- TODO: manual review — unexpected token after 'italic_font auto'
-- TODO: manual review — unexpected token after 'bold_italic_font auto'

-- TODO: manual review — unexpected token after 'cursor_shape beam'
-- TODO: manual review — unexpected token after 'cursor_blink_interval 0.5'
-- TODO: manual review — unexpected token after 'enable_audio_bell no'
-- TODO: manual review — unexpected token after 'confirm_os_window_close 0'
-- TODO: manual review — unexpected token after 'window_padding_width 8'
-- TODO: manual review — unexpected token after 'background_opacity 0.94'
-- TODO: manual review — unexpected token after 'tab_bar_edge top'
-- TODO: manual review — unexpected token after 'shell_integration enabled'
-- TODO: manual review — unexpected token after 'allow_remote_control yes'
-- TODO: manual review — unexpected token after 'listen_on unix'
