[general]
bars = 0
bar_width = 1
bar_spacing = 0
framerate = 144
sensitivity = 300
autosens = 0

[input]
method = pulse
source = auto

[output]
method = ncurses
channels = mono
mono_option = average
reverse = 0
bar_delimiter = 0

[smoothing]
integral = 77
monstercat = 1
noise_reduction = 0.77
waves = 1
gravity = 80

[eq]
1 = 0.8
2 = 1.0
3 = 1.0
4 = 1.0
5 = 1.0
6 = 1.0
7 = 1.0
8 = 0.9

[color]
gradient = 1
gradient_count = 5
gradient_color_1 = '#1a1535'
gradient_color_2 = '#3d59a1'
gradient_color_3 = '#6b94c4'
gradient_color_4 = '#b17dff'
gradient_color_5 = '#e0d4ff'
foreground = '#b17dff'
background = '#0f0d14'
