[general]
bars = 0
bar_width = 1
bar_spacing = 1
framerate = 144
sensitivity = 380
autosens = 0

[input]
method = pulse
source = auto

[output]
method = ncurses
channels = mono
mono_option = average
reverse = 0
bar_delimiter = 0

[smoothing]
integral = 95
monstercat = 1
noise_reduction = 0.88
waves = 0
gravity = 140

[eq]
1 = 0.8
2 = 1.0
3 = 1.0
4 = 1.0
5 = 1.0
6 = 1.0
7 = 1.0
8 = 0.9

[color]
gradient = 1
gradient_count = 8
gradient_color_1 = '#001122'
gradient_color_2 = '#002244'
gradient_color_3 = '#004488'
gradient_color_4 = '#0088FF'
gradient_color_5 = '#00FFFF'
gradient_color_6 = '#88FFFF'
gradient_color_7 = '#CCAAFF'
gradient_color_8 = '#FFEEFF'
background = '#0a0a0a'
foreground = '#CCAAFF'
