[general]
bars = 12
bar_width = 3
bar_spacing = 1
framerate = 60
sensitivity = 120

[input]
method = pulse
source = auto

[output]
method = ncurses
channels = stereo
mono_option = average
reverse = 0
bar_delimiter = 0
data_format = ascii
ascii_max_range = 7

[smoothing]
integral = 70
monstercat = 1
waves = 1

[eq]
1 = 1
2 = 1
3 = 1
4 = 1
5 = 1
6 = 1
7 = 1
8 = 1

[color]
gradient = 1
gradient_count = 3
gradient_color_1 = '#3d5a7a'
gradient_color_2 = '#6b94c4'
gradient_color_3 = '#b17dff'
foreground = '#f6f2ff'
background = '#0f0d14'
