-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local bg = "rgb(0f0d14)"
local primary = "rgb(6b94c4)"
local secondary = "rgb(3d5a7a)"
local accent = "rgb(b17dff)"
local text = "rgb(f6f2ff)"
