foreground #f6f2ff
background #0f0d14
selection_foreground #0f0d14
selection_background #b17dff
cursor #b17dff
cursor_text_color #0f0d14
url_color #5b6c84
active_border_color #b17dff
inactive_border_color #5b6c84
active_tab_background #4f433b
active_tab_foreground #f6f2ff
inactive_tab_background #1b1622
inactive_tab_foreground #f6f2ff
color0 #0f0d14
color1 #4f433b
color2 #5b6c84
color3 #b17dff
color4 #77665a
color5 #7863b5
color6 #d9c4ff
color7 #f6f2ff
color8 #28222f
color9 #67574d
color10 #70839c
color11 #c59dff
color12 #95867a
color13 #927ad4
color14 #eadbff
color15 #fdfaff
