foreground #f6f2ff
background #0f0d14
selection_foreground #0f0d14
selection_background #b17dff
cursor #b17dff
cursor_text_color #0f0d14
url_color #6b94c4
active_border_color #b17dff
inactive_border_color #3d5a7a
active_tab_background #6b94c4
active_tab_foreground #0f0d14
inactive_tab_background #1b1622
inactive_tab_foreground #f6f2ff
color0 #0f0d14
color1 #6b94c4
color2 #3d5a7a
color3 #b17dff
color4 #85acd6
color5 #7863b5
color6 #d9c4ff
color7 #f6f2ff
color8 #28222f
color9 #82b0db
color10 #4e7396
color11 #c59dff
color12 #9ec1e8
color13 #927ad4
color14 #eadbff
color15 #fdfaff
