[general]
bars = 0
bar_width = 1
bar_spacing = 0
framerate = 144
sensitivity = 250
autosens = 0

[input]
method = pulse
source = auto

[output]
method = ncurses
channels = mono
mono_option = average
reverse = 0
bar_delimiter = 0

[smoothing]
integral = 77
monstercat = 1
noise_reduction = 0.77
waves = 1
gravity = 80

[eq]
1 = 0.8
2 = 1.0
3 = 1.0
4 = 1.0
5 = 1.0
6 = 1.0
7 = 1.0
8 = 0.9

[color]
gradient = 1
gradient_count = 5
gradient_color_1 = '#1a1230'
gradient_color_2 = '#2d2d5f'
gradient_color_3 = '#af91ea'
gradient_color_4 = '#f0b43c'
gradient_color_5 = '#f7eeff'
foreground = '#af91ea'
background = '#100d16'
