[general]
bars = 64
bar_width = 3
bar_spacing = 1
framerate = 144
sensitivity = 180
autosens = 1

[input]
method = pulse
source = auto

[output]
method = ncurses
channels = stereo
mono_option = average
reverse = 0
bar_delimiter = 0

[smoothing]
integral = 90
monstercat = 1
noise_reduction = 0.88
waves = 1
gravity = 130
ignore = 0

[eq]
1 = 1
2 = 1
3 = 1
4 = 1
5 = 1
6 = 1
7 = 1
8 = 1

[color]
gradient = 1
gradient_count = 4
gradient_color_1 = '#af91ea'
gradient_color_2 = '#f0b43c'
gradient_color_3 = '#f7eeff'
gradient_color_4 = '#ffffff'
foreground = '#f7eeff'
background = '#100d16'
