[general]
bars = 0
bar_width = 2
bar_spacing = 1
framerate = 144
sensitivity = 100
autosens = 1

[input]
method = pulse
source = auto

[output]
method = ncurses
channels = mono
mono_option = average

[smoothing]
integral = 95
monstercat = 1
noise_reduction = 0.88
waves = 0
gravity = 140

[color]
gradient = 1
gradient_count = 8
gradient_color_1 = '#19131D'
gradient_color_2 = '#2B255D'
gradient_color_3 = '#583746'
gradient_color_4 = '#57449D'
gradient_color_5 = '#9F5346'
gradient_color_6 = '#956BBE'
gradient_color_7 = '#DBAB4D'
gradient_color_8 = '#D5BAD7'
background = '#0a0a0a'
foreground = '#DBAB4D'
