-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local bg = "rgb(100d16)"
local primary = "rgb(af91ea)"
local secondary = "rgb(2d2d3f)"
local accent = "rgb(f0b43c)"
local text = "rgb(f7eeff)"
