foreground #f7eeff
background #100d16
selection_foreground #100d16
selection_background #f0b43c
cursor #f0b43c
cursor_text_color #100d16
url_color #af91ea
active_border_color #f0b43c
inactive_border_color #2d2d3f
active_tab_background #af91ea
active_tab_foreground #100d16
inactive_tab_background #1d1827
inactive_tab_foreground #f7eeff
color0 #100d16
color1 #af91ea
color2 #2d2d3f
color3 #f0b43c
color4 #c3b1f3
color5 #7e6bc0
color6 #ffd47c
color7 #f7eeff
color8 #2a2434
color9 #c9b5ff
color10 #43435b
color11 #f8c964
color12 #dccdff
color13 #9886d6
color14 #ffe3a4
color15 #fdf9ff
