-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local bg = "rgb(08111f)"
local primary = "rgb(2d66df)"
local secondary = "rgb(158fc7)"
local accent = "rgb(89ebff)"
local text = "rgb(ecf7ff)"
