foreground #ecf7ff
background #08111f
selection_foreground #08111f
selection_background #89ebff
cursor #89ebff
cursor_text_color #08111f
url_color #2d66df
active_border_color #89ebff
inactive_border_color #158fc7
active_tab_background #2d66df
active_tab_foreground #08111f
inactive_tab_background #0e1d34
inactive_tab_foreground #ecf7ff
color0 #08111f
color1 #2d66df
color2 #158fc7
color3 #89ebff
color4 #4a82ef
color5 #2fb8f0
color6 #b5f6ff
color7 #ecf7ff
color8 #1a2f4f
color9 #4c83f6
color10 #2ba6de
color11 #a8f4ff
color12 #6d9dff
color13 #59c9ff
color14 #d8fcff
color15 #fbfeff
