-- TODO: manual review — unexpected token after 'foreground'
--ecf7ff
-- TODO: manual review — unexpected token after 'background'
--08111f
-- TODO: manual review — unexpected token after 'selection_foreground'
--08111f
-- TODO: manual review — unexpected token after 'selection_background'
--89ebff
-- TODO: manual review — unexpected token after 'cursor'
--89ebff
-- TODO: manual review — unexpected token after 'cursor_text_color'
--08111f
-- TODO: manual review — unexpected token after 'url_color'
--2d66df
-- TODO: manual review — unexpected token after 'active_border_color'
--89ebff
-- TODO: manual review — unexpected token after 'inactive_border_color'
--158fc7
-- TODO: manual review — unexpected token after 'active_tab_background'
--2d66df
-- TODO: manual review — unexpected token after 'active_tab_foreground'
--08111f
-- TODO: manual review — unexpected token after 'inactive_tab_background'
--0e1d34
-- TODO: manual review — unexpected token after 'inactive_tab_foreground'
--ecf7ff
-- TODO: manual review — unexpected token after 'color0'
--08111f
-- TODO: manual review — unexpected token after 'color1'
--2d66df
-- TODO: manual review — unexpected token after 'color2'
--158fc7
-- TODO: manual review — unexpected token after 'color3'
--89ebff
-- TODO: manual review — unexpected token after 'color4'
--4a82ef
-- TODO: manual review — unexpected token after 'color5'
--2fb8f0
-- TODO: manual review — unexpected token after 'color6'
--b5f6ff
-- TODO: manual review — unexpected token after 'color7'
--ecf7ff
-- TODO: manual review — unexpected token after 'color8'
--1a2f4f
-- TODO: manual review — unexpected token after 'color9'
--4c83f6
-- TODO: manual review — unexpected token after 'color10'
--2ba6de
-- TODO: manual review — unexpected token after 'color11'
--a8f4ff
-- TODO: manual review — unexpected token after 'color12'
--6d9dff
-- TODO: manual review — unexpected token after 'color13'
--59c9ff
-- TODO: manual review — unexpected token after 'color14'
--d8fcff
-- TODO: manual review — unexpected token after 'color15'
--fbfeff
