[general]
bars = 0
bar_width = 2
bar_spacing = 1
framerate = 144
sensitivity = 100
autosens = 1

[input]
method = pulse
source = auto

[output]
method = ncurses
channels = mono
mono_option = average

[smoothing]
integral = 95
monstercat = 1
noise_reduction = 0.88
waves = 0
gravity = 140

[color]
gradient = 1
gradient_count = 8
gradient_color_1 = '#15200F'
gradient_color_2 = '#2B541F'
gradient_color_3 = '#565B30'
gradient_color_4 = '#966932'
gradient_color_5 = '#5E9E3D'
gradient_color_6 = '#BCC74E'
gradient_color_7 = '#C6D1A0'
gradient_color_8 = '#ECEEE2'
background = '#0a0a0a'
foreground = '#C6D1A0'
