-- TODO: manual review — unexpected token after '[general]'
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — top-level key 'bars = 0' has no enclosing section
-- TODO: manual review — top-level key 'bar_width = 2' has no enclosing section
-- TODO: manual review — top-level key 'bar_spacing = 1' has no enclosing section
-- TODO: manual review — top-level key 'framerate = 144' has no enclosing section
-- TODO: manual review — top-level key 'sensitivity = 100' has no enclosing section
-- TODO: manual review — top-level key 'autosens = 1' has no enclosing section

-- TODO: manual review — unexpected token after '[input]'
-- TODO: manual review — top-level key 'method = pulse' has no enclosing section
-- Source: auto — convert this file to Lua and ensure it is on Lua's package.path.
require("auto")

-- TODO: manual review — unexpected token after '[output]'
-- TODO: manual review — top-level key 'method = ncurses' has no enclosing section
-- TODO: manual review — top-level key 'channels = mono' has no enclosing section
-- TODO: manual review — top-level key 'mono_option = average' has no enclosing section

-- TODO: manual review — unexpected token after '[smoothing]'
-- TODO: manual review — top-level key 'integral = 95' has no enclosing section
-- TODO: manual review — top-level key 'monstercat = 1' has no enclosing section
-- TODO: manual review — top-level key 'noise_reduction = 0.88' has no enclosing section
-- TODO: manual review — top-level key 'waves = 0' has no enclosing section
-- TODO: manual review — top-level key 'gravity = 140' has no enclosing section

-- TODO: manual review — unexpected token after '[color]'
-- TODO: manual review — top-level key 'gradient = 1' has no enclosing section
-- TODO: manual review — top-level key 'gradient_count = 8' has no enclosing section
-- TODO: manual review — top-level key 'gradient_color_1 = '' has no enclosing section
-- TODO: manual review — top-level key 'gradient_color_2 = '' has no enclosing section
-- TODO: manual review — top-level key 'gradient_color_3 = '' has no enclosing section
-- TODO: manual review — top-level key 'gradient_color_4 = '' has no enclosing section
-- TODO: manual review — top-level key 'gradient_color_5 = '' has no enclosing section
-- TODO: manual review — top-level key 'gradient_color_6 = '' has no enclosing section
-- TODO: manual review — top-level key 'gradient_color_7 = '' has no enclosing section
-- TODO: manual review — top-level key 'gradient_color_8 = '' has no enclosing section
-- TODO: manual review — top-level key 'background = '' has no enclosing section
-- TODO: manual review — top-level key 'foreground = '' has no enclosing section
