[general]
bars = 64
bar_width = 2
bar_spacing = 1
framerate = 144
sensitivity = 100
autosens = 1

[input]
method = pulse
source = auto

[output]
method = ncurses
channels = mono
mono_option = average

[smoothing]
integral = 95
monstercat = 1
noise_reduction = 0.88
waves = 0
gravity = 140

[color]
gradient = 1
gradient_count = 8
gradient_color_1 = '#002200'
gradient_color_2 = '#004400'
gradient_color_3 = '#008800'
gradient_color_4 = '#00FF00'
gradient_color_5 = '#44FF00'
gradient_color_6 = '#88FF00'
gradient_color_7 = '#CCFF00'
gradient_color_8 = '#FFFF00'
background = '#0a0a0a'
foreground = '#CCFF00'

