[general]
bars = 0
bar_width = 1
bar_spacing = 0
framerate = 144
sensitivity = 190
autosens = 0

[input]
method = pulse
source = auto

[output]
method = ncurses
channels = mono
mono_option = average
reverse = 0
bar_delimiter = 0

[smoothing]
integral = 77
monstercat = 1
noise_reduction = 0.77
waves = 1
gravity = 125

[eq]
1 = 0.8
2 = 1.0
3 = 1.0
4 = 1.0
5 = 1.0
6 = 1.0
7 = 1.0
8 = 0.9

[color]
gradient = 1
gradient_count = 5
gradient_color_1 = '#072b09'
gradient_color_2 = '#21441f'
gradient_color_3 = '#59d74d'
gradient_color_4 = '#e0b14a'
gradient_color_5 = '#f6fbef'
foreground = '#e0b14a'
background = '#081209'
