-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local bg = "rgb(081209)"
local primary = "rgb(59d74d)"
local secondary = "rgb(21441f)"
local accent = "rgb(e0b14a)"
local text = "rgb(f6fbef)"
