foreground #f6fbef
background #081209
selection_foreground #081209
selection_background #e0b14a
cursor #e0b14a
cursor_text_color #081209
url_color #59d74d
active_border_color #e0b14a
inactive_border_color #21441f
active_tab_background #59d74d
active_tab_foreground #081209
inactive_tab_background #122014
inactive_tab_foreground #f6fbef
color0 #081209
color1 #59d74d
color2 #21441f
color3 #e0b14a
color4 #85e55e
color5 #3bbf57
color6 #f2db8b
color7 #f6fbef
color8 #1a2d1d
color9 #74ee68
color10 #2b5f2b
color11 #eac86c
color12 #9bf477
color13 #57d074
color14 #f7e7b0
color15 #fcfef8
