-- TODO: manual review — unexpected token after 'foreground'
--f6fbef
-- TODO: manual review — unexpected token after 'background'
--081209
-- TODO: manual review — unexpected token after 'selection_foreground'
--081209
-- TODO: manual review — unexpected token after 'selection_background'
--e0b14a
-- TODO: manual review — unexpected token after 'cursor'
--e0b14a
-- TODO: manual review — unexpected token after 'cursor_text_color'
--081209
-- TODO: manual review — unexpected token after 'url_color'
--59d74d
-- TODO: manual review — unexpected token after 'active_border_color'
--e0b14a
-- TODO: manual review — unexpected token after 'inactive_border_color'
--21441f
-- TODO: manual review — unexpected token after 'active_tab_background'
--59d74d
-- TODO: manual review — unexpected token after 'active_tab_foreground'
--081209
-- TODO: manual review — unexpected token after 'inactive_tab_background'
--122014
-- TODO: manual review — unexpected token after 'inactive_tab_foreground'
--f6fbef
-- TODO: manual review — unexpected token after 'color0'
--081209
-- TODO: manual review — unexpected token after 'color1'
--59d74d
-- TODO: manual review — unexpected token after 'color2'
--21441f
-- TODO: manual review — unexpected token after 'color3'
--e0b14a
-- TODO: manual review — unexpected token after 'color4'
--85e55e
-- TODO: manual review — unexpected token after 'color5'
--3bbf57
-- TODO: manual review — unexpected token after 'color6'
--f2db8b
-- TODO: manual review — unexpected token after 'color7'
--f6fbef
-- TODO: manual review — unexpected token after 'color8'
--1a2d1d
-- TODO: manual review — unexpected token after 'color9'
--74ee68
-- TODO: manual review — unexpected token after 'color10'
--2b5f2b
-- TODO: manual review — unexpected token after 'color11'
--eac86c
-- TODO: manual review — unexpected token after 'color12'
--9bf477
-- TODO: manual review — unexpected token after 'color13'
--57d074
-- TODO: manual review — unexpected token after 'color14'
--f7e7b0
-- TODO: manual review — unexpected token after 'color15'
--fcfef8
