[general]
bars = 0
bar_width = 2
bar_spacing = 1
framerate = 144
sensitivity = 100
autosens = 1

[input]
method = pulse
source = auto

[output]
method = ncurses
channels = mono
mono_option = average

[smoothing]
integral = 95
monstercat = 1
noise_reduction = 0.88
waves = 0
gravity = 140

[color]
gradient = 1
gradient_count = 8
gradient_color_1 = '#170909'
gradient_color_2 = '#5A1B16'
gradient_color_3 = '#613354'
gradient_color_4 = '#9C2916'
gradient_color_5 = '#9052A2'
gradient_color_6 = '#D6532C'
gradient_color_7 = '#FAA258'
gradient_color_8 = '#F2D5AD'
background = '#0a0a0a'
foreground = '#FAA258'
