-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local bg = "rgb(120807)"
local primary = "rgb(ee5a21)"
local secondary = "rgb(7c3ab4)"
local accent = "rgb(ffb37a)"
local text = "rgb(faecff)"
