foreground #faecff
background #120807
selection_foreground #120807
selection_background #ffb37a
cursor #ffb37a
cursor_text_color #120807
url_color #ee5a21
active_border_color #ffb37a
inactive_border_color #7c3ab4
active_tab_background #ee5a21
active_tab_foreground #120807
inactive_tab_background #241111
inactive_tab_foreground #faecff
color0 #120807
color1 #ee5a21
color2 #7c3ab4
color3 #ffb37a
color4 #ff7b4a
color5 #9d59d2
color6 #ffd0ac
color7 #faecff
color8 #311816
color9 #ff8257
color10 #9450ca
color11 #ffc191
color12 #ff986f
color13 #b27ae1
color14 #ffe0c6
color15 #fff9ff
