-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    general = {
        border_size = 3,
        col = {
            active_border = accent .. " " .. primary .. " 55deg",
            inactive_border = secondary,
        },
    },
    decoration = {
        rounding = 12,
        active_opacity = 0.98,
        inactive_opacity = 0.94,
        shadow = {
            enabled = true,
            range = 26,
            render_power = 3,
            color = bg,
        },
    },
    group = {
        col = {
            border_active = accent,
            border_inactive = secondary,
        },
    },
})

