general {
    border_size = 4
    col.active_border = $accent $primary 45deg
    col.inactive_border = $secondary
}

decoration {
    rounding = 8
    active_opacity = 0.97
    inactive_opacity = 0.93

    blur {
        enabled = true
        size = 12
        passes = 4
        vibrancy = 0.28
        noise = 0.02
        contrast = 1.1
        brightness = 1.0
    }

    shadow {
        enabled = true
        range = 22
        render_power = 3
        color = $bg
    }
}

group {
    col.border_active = $accent
    col.border_inactive = $secondary
}
