# BitBeast theme state
source = ~/.config/bitbeast/current.conf
source = ~/.config/hypr/bitbeast-theme.conf

monitor = ,preferred,auto,1

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

$mod = SUPER
$terminal = kitty
$menu = rofi -show drun -config ~/.config/rofi/config.rasi

exec-once = swww-daemon
exec-once = waybar

input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0
}

general {
    gaps_in = 6
    gaps_out = 12
    layout = dwindle
    allow_tearing = false
}

dwindle {
    pseudotile = true
    preserve_split = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

bind = $mod, RETURN, exec, $terminal
bind = $mod, Q, killactive
bind = $mod, F, fullscreen
bind = $mod, SPACE, togglefloating
bind = $mod, R, exec, $menu
