-- ─── BitBeast Hyprlock — Aesthetic Edition ────────────────────────────────────
-- Modern, minimalist layout with blurred background and glassmorphism elements.
-- Colors and assets injected via `bitbeast-lock-colors.conf`.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/bitbeast-lock-colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("bitbeast-lock-colors")

hl.curve("sharp", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.curve("smooth", { type = "bezier", points = { { 0.25, 1.0 }, { 0.35, 1.0 } } })
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 5.0,
    bezier = "smooth",
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 3.0,
    bezier = "smooth",
})
hl.animation({
    leaf = "inputFieldFade",
    enabled = true,
    speed = 4.0,
    bezier = "sharp",
})
hl.animation({
    leaf = "inputFieldWidth",
    enabled = true,
    speed = 4.0,
    bezier = "sharp",
})
hl.animation({
    leaf = "inputFieldDots",
    enabled = true,
    speed = 3.0,
    bezier = "smooth",
})

-- TODO: manual review — unknown section 'background {' on line 27

-- TODO: manual review — unknown section 'label {' on line 39

-- TODO: manual review — unknown section 'label {' on line 55

-- TODO: manual review — unknown section 'label {' on line 68

-- TODO: manual review — unknown section 'image {' on line 81

-- TODO: manual review — unknown section 'shape {' on line 95

-- TODO: manual review — unknown section 'label {' on line 108

-- TODO: manual review — unknown section 'input-field {' on line 121

-- TODO: manual review — unknown section 'label {' on line 145

-- TODO: manual review — unknown section 'label {' on line 159

-- TODO: manual review — unknown section 'label {' on line 173

-- TODO: manual review — unknown section 'label {' on line 187

-- TODO: manual review — unknown section 'label {' on line 202
hl.config({
    general = {
        hide_cursor = false,
        immediate_render = true,
        text_trim = true,
    },
    -- ── Animations ────────────────────────────────────────────────────────────────
    animations = {
        enabled = true,
    },
    -- ── Background ────────────────────────────────────────────────────────────────
    -- ── Day of Week ───────────────────────────────────────────────────────────────
    -- ── Date ──────────────────────────────────────────────────────────────────────
    -- ── Time ──────────────────────────────────────────────────────────────────────
    -- ── Profile Avatar ───────────────────────────────────────────────────────────
    -- ── Username Pill ────────────────────────────────────────────────────────────
    -- ── Password Field ───────────────────────────────────────────────────────────
    -- ── Power Menu ────────────────────────────────────────────────────────────────
    -- ── Theme Badge ──────────────────────────────────────────────────────────────
})

