-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — top-level key 'autogenerated = 0' has no enclosing section

-- BitBeast theme state
-- Source: ~/.config/bitbeast/current.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("current")
-- Source: ~/.config/hypr/bitbeast-theme.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("bitbeast-theme")

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
-- env = XCURSOR_THEME,Adwaita
-- env = HYPRCURSOR_THEME,Adwaita

local mod = "SUPER"
local terminal = "kitty"
local browser = "google-chrome-stable"
local menu = "rofi -show drun -config ~/.config/rofi/config.rasi"
local bitbeast = "~/.local/bin/bitbeast"
hl.workspace_rule({
    workspace = "1",
    persistent = true,
})

hl.workspace_rule({
    workspace = "2",
    persistent = true,
})

hl.workspace_rule({
    workspace = "3",
    persistent = true,
})

hl.workspace_rule({
    workspace = "4",
    persistent = true,
})

hl.workspace_rule({
    workspace = "5",
    persistent = true,
})

hl.workspace_rule({
    workspace = "6",
    persistent = true,
})

hl.workspace_rule({
    workspace = "7",
    persistent = true,
})

hl.workspace_rule({
    workspace = "8",
    persistent = true,
})

hl.layer_rule({
    name = "rofi",
    blur = true,
    ignore_alpha = 0.1,
})

hl.layer_rule({
    name = "waybar",
    -- TODO: manual review — disable "blur" has no layer_rule directive analog
    -- TODO: manual review — unmapped layer rule: "ignore_alpha"
})

hl.layer_rule({
    name = "bitbeast-osd",
    blur = true,
    ignore_alpha = 0.2,
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})
hl.gesture({
    fingers = 3,
    direction = "up",
    action = "dispatcher",
    -- TODO: manual review — extra gesture field "exec"
    -- TODO: manual review — extra gesture field "~/.local/bin/bitbeast-workspaces"
})

hl.bind(mod .. " + Return", hl.dsp.exec_cmd(terminal .. " -e bash -c \"fastfetch --config ~/.config/fastfetch/config.jsonc; exec $SHELL\""))
hl.bind(mod .. " + SHIFT + Return", hl.dsp.exec_cmd("kitty --class=\"dropdown\""))

hl.bind(mod .. " + r", hl.dsp.exec_cmd(menu))
hl.bind(mod .. " + b", hl.dsp.exec_cmd(browser))
hl.bind(mod .. " + o", hl.dsp.exec_cmd("~/.local/bin/bongocat"))
hl.bind(mod .. " + e", hl.dsp.exec_cmd("dolphin"))
hl.bind(mod .. " + h", hl.dsp.exec_cmd(bitbeast .. " keybindings"))
hl.bind(mod .. " + E", hl.dsp.exec_cmd(terminal .. " -e yazi"))
hl.bind(mod .. " + W", hl.dsp.exec_cmd(bitbeast .. " pick"))
hl.bind(mod .. " + SHIFT + W", hl.dsp.exec_cmd(bitbeast .. " style cycle"))
hl.bind(mod .. " + SHIFT + r", hl.dsp.exec_cmd(bitbeast .. " gradient"))

hl.bind(mod .. " + SHIFT + B", hl.dsp.exec_cmd(bitbeast .. " pick-style"))

hl.bind(mod .. " + T", hl.dsp.exec_cmd(bitbeast .. " zsh cycle"))
hl.bind(mod .. " + SHIFT + T", hl.dsp.exec_cmd(bitbeast .. " zsh pick"))

hl.bind(mod .. " + SHIFT + P", hl.dsp.exec_cmd(bitbeast .. " touchpad"))

hl.bind(mod .. " + CTRL + T", hl.dsp.exec_cmd(bitbeast .. " auto-theme"))

hl.bind(mod .. " + q", hl.dsp.window.close())
hl.bind(mod .. " + SHIFT + q", hl.dsp.exit())
hl.bind("CTRL + ALT + Delete", hl.dsp.exit())

hl.bind(mod .. " + f", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mod .. " + CTRL + f", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mod .. " + space", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + ALT + space", hl.dsp.exec_cmd("hyprctl dispatch workspaceopt allfloat"))
hl.bind(mod .. " + SHIFT + I", hl.dsp.layout("togglesplit"))
hl.bind(mod .. " + P", hl.dsp.window.pseudo())

hl.bind("CTRL + ALT + L", hl.dsp.exec_cmd("~/.local/bin/bitbeast lock"))
hl.bind(mod .. " + L", hl.dsp.exec_cmd("~/.local/bin/bitbeast lock"))
hl.bind(mod .. " + SHIFT + E", hl.dsp.exec_cmd(bitbeast .. " session-init"))

hl.bind(mod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mod .. " + j", hl.dsp.focus({ direction = "down" }))

hl.bind(mod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mod .. " + SHIFT + h", hl.dsp.window.move({ direction = "l" }))
hl.bind(mod .. " + SHIFT + l", hl.dsp.window.move({ direction = "r" }))
hl.bind(mod .. " + SHIFT + k", hl.dsp.window.move({ direction = "u" }))
hl.bind(mod .. " + SHIFT + j", hl.dsp.window.move({ direction = "d" }))

hl.bind(mod .. " + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mod .. " + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mod .. " + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mod .. " + SHIFT + down", hl.dsp.window.move({ direction = "d" }))

hl.bind(mod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize())

hl.bind(mod .. " + CTRL + h", hl.dsp.window.resize({ x = -30, y = 0, relative = true }), { repeating = true })
hl.bind(mod .. " + CTRL + l", hl.dsp.window.resize({ x = 30, y = 0, relative = true }), { repeating = true })
hl.bind(mod .. " + CTRL + k", hl.dsp.window.resize({ x = 0, y = -30, relative = true }), { repeating = true })
hl.bind(mod .. " + CTRL + j", hl.dsp.window.resize({ x = 0, y = 30, relative = true }), { repeating = true })
hl.bind(mod .. " + CTRL + left", hl.dsp.window.resize({ x = -30, y = 0, relative = true }), { repeating = true })
hl.bind(mod .. " + CTRL + right", hl.dsp.window.resize({ x = 30, y = 0, relative = true }), { repeating = true })
hl.bind(mod .. " + CTRL + up", hl.dsp.window.resize({ x = 0, y = -30, relative = true }), { repeating = true })
hl.bind(mod .. " + CTRL + down", hl.dsp.window.resize({ x = 0, y = 30, relative = true }), { repeating = true })

hl.bind(mod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mod .. " + Tab", hl.dsp.focus({ workspace = "m+1" }))
hl.bind(mod .. " + SHIFT + Tab", hl.dsp.focus({ workspace = "m-1" }))

hl.bind(mod .. " + CTRL + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind(mod .. " + CTRL + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind(mod .. " + CTRL + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind(mod .. " + CTRL + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind(mod .. " + CTRL + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind(mod .. " + CTRL + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
hl.bind(mod .. " + CTRL + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
hl.bind(mod .. " + CTRL + 8", hl.dsp.window.move({ workspace = 8, follow = false }))

hl.bind(mod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))

hl.bind(mod .. " + SHIFT + U", hl.dsp.window.move({ workspace = "special" }))
hl.bind(mod .. " + U", hl.dsp.workspace.toggle_special(""))

hl.bind(mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("~/.local/bin/bitbeast-osd brightness raise"), { repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("~/.local/bin/bitbeast-osd brightness lower"), { repeating = true })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("~/.local/bin/bitbeast-osd volume raise"), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("~/.local/bin/bitbeast-osd volume lower"), { repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("~/.local/bin/bitbeast-osd volume mute"))
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"))

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

hl.bind(mod .. " + s", hl.dsp.exec_cmd("mkdir -p ~/Pictures/Screenshots && grim -g \"$(slurp)\" - | tee ~/Pictures/Screenshots/$(date +'%Y-%m-%d-%H%M%S').png | wl-copy"))
hl.bind(mod .. " + SHIFT + s", hl.dsp.exec_cmd("mkdir -p ~/Pictures/Screenshots && grim - | tee ~/Pictures/Screenshots/$(date +'%Y-%m-%d-%H%M%S').png | wl-copy"))
hl.bind(mod .. " + v", hl.dsp.exec_cmd(bitbeast .. " clipboard"))
hl.bind(mod .. " + A", hl.dsp.exec_cmd("~/.local/bin/toggle-transparency"))

hl.window_rule({
    match = {
        class = "^(bitbeast-visualizer)$",
    },
    float = true,
    pin = true,
    center = true,
    size = "800 350",
    border_size = 0,
})

hl.window_rule({
    match = {
        class = "^(Bongo-cat)$",
    },
    float = true,
    pin = true,
    center = true,
    size = "420 420",
    border_size = 0,
})

hl.window_rule({
    match = {
        class = "^(bitbeast-hints)$",
    },
    float = true,
    pin = true,
    center = true,
    size = "1080 720",
    border_size = 0,
})

-- Source: ~/.config/hypr/touchpad.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("touchpad")

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.curve("linear", { type = "bezier", points = { { 0.0, 0.0 }, { 1.0, 1.0 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 7,
    bezier = "myBezier",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 7,
    bezier = "default",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 30,
    bezier = "linear",
    style = "loop",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 7,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6,
    bezier = "default",
})
hl.config({
    input = {
        kb_layout = "us",
        follow_mouse = 1,
        natural_scroll = true,
        sensitivity = 0,
        touchpad = {
            natural_scroll = true,
        },
    },
    general = {
        gaps_in = 6,
        gaps_out = 12,
        layout = "dwindle",
        allow_tearing = false,
    },
    dwindle = {
        preserve_split = true,
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
    -- Touchpad Gestures
    -- 3-finger horizontal → switch workspace
    -- 3-finger up → workspace overview
    -- 4-finger vertical swipe → volume (bitbeast-volume-gesture + OSD)
    -- 4-finger tap → play/pause media (bitbeast-volume-gesture)
    -- Terminal
    -- Execution and Launchers
    -- Waybar Style Picker (nice named styles)
    -- Zsh Theme
    -- Touchpad Sensitivity Selector
    -- Auto Theme from Wallpaper
    -- Window Management
    -- Desktop/Workspace
    -- Window focus (vim keys)
    -- Window focus (arrow keys)
    -- Move windows (vim keys)
    -- Move windows (arrow keys)
    -- Hold SUPER and drag an app with mouse to move/resize it
    -- Resize windows
    -- Workspaces
    -- Send active app to a workspace and stay on the current workspace
    -- Send active app to a workspace and follow it
    -- Special workspace
    -- Scroll through existing workspaces
    -- Brightness
    -- Volume
    -- Media Keys
    -- Screenshot
    -- Visualizer Rules
    -- BongoCat Rules
    -- Hints Rules
    -- Touchpad Configuration
    animations = {
        enabled = true,
    },
})

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd(bitbeast .. " session-init")
    hl.exec_cmd("~/.local/bin/bitbeast-battery-watcher")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)

