-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local bg = "rgb(150608)"
local primary = "rgb(e8450c)"
local secondary = "rgb(7b120f)"
local accent = "rgb(ffd166)"
local text = "rgb(fff1dd)"
